# Generated by Django 4.0.3 on 2022-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
